# Inline configuration
# Level: Project (standalone)

branches:
  - main
  - name: beta
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: |
        # Update Python version in pyproject.toml
        sed -i.bak 's/^version = .*/version = "${nextRelease.version}"/' pyproject.toml && rm pyproject.toml.bak
        # Update Python version in src/__init__.py
        sed -i.bak 's/^__version__ = .*/__version__ = "${nextRelease.version}"/' src/__init__.py && rm src/__init__.py.bak
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - pyproject.toml
        - src/__init__.py
  - "@semantic-release/github"
